In [1]:
import torch
import numpy as np

**Tensor Math operation**

In [14]:
tensor_a=torch.tensor([2,4,6,8])
tensor_b=torch.tensor([1,3,5,7])

In [15]:
#addition
tensor_a+tensor_b

tensor([ 3,  7, 11, 15])

In [16]:
#addition long hand
torch.add(tensor_a,tensor_b)


tensor([ 3,  7, 11, 15])

In [18]:
#sub function
torch.sub(tensor_a,tensor_b)

tensor([1, 1, 1, 1])

In [19]:
#Multiplication
tensor_a*tensor_b

tensor([ 2, 12, 30, 56])

In [21]:
#Multiplication long hand
torch.mul(tensor_a,tensor_b)

tensor([ 2, 12, 30, 56])

In [20]:
#Divison
tensor_a/tensor_b

tensor([2.0000, 1.3333, 1.2000, 1.1429])

In [22]:
#long hand divion
torch.div(tensor_a,tensor_b)

tensor([2.0000, 1.3333, 1.2000, 1.1429])

In [23]:
#Long reminder module
torch.remainder(tensor_a,tensor_b)

tensor([0, 1, 1, 1])

In [24]:
#reminder module
tensor_a % tensor_b

tensor([0, 1, 1, 1])

In [25]:
# Exponent / power
torch.pow(tensor_a,tensor_b)

tensor([      2,      64,    7776, 2097152])

In [ ]:
# reassignment
